general {
  #colors = false
  color_good = "#23fe54"
  #color_degraded = "#$fg"
  color_bad = "#fb414a"
  interval = 1
  separator = ":||:"
}

order += "battery 0"
order += "cpu_usage"
order += "memory"
order += "load"
order += "cpu_temperature 0"
order += "disk /"
order += "ethernet eno1"
order += "wireless wlo1"
order += "volume master"
order += "time"

battery 0 {
        #format = "%status %percentage %remaining %emptytime"
        format = "%status %percentage (%remaining left @ %consumption)"
        format_down = "No battery"
        status_chr = "B_c:"
        status_bat = "B_d:"
        status_unk = "?:"
        status_full = "B_f:"
        status_idle = "☻ IDLE:"
        path = "/sys/class/power_supply/BAT%d/uevent"
        low_threshold = 30
}

disk "/" {
  format = "/: (%free free)"
  #format = "/ : %used/%total"
}

cpu_usage {
  # format = "Cpu: %cpu0 %cpu1 %cpu2 %cpu3 %cpu4 %cpu5 %cpu6 %cpu7 %cpu8 %cpu9 %cpu10 %cpu11 %cpu12 %cpu13 %cpu14 %cpu15"
  format = "C: %usage"
  max_threshold = 25
}

memory {
  memory_used_method = classical
  format="M: %available"
  unit="auto"
  decimals="2"
}

time {
  format = "D: %d %b, %a | T: %H:%M:%S"
}

load {
  #format = "%1min, %5min, %15min"
  format = "L: %1min, %15min"
  max_threshold = "2.0"
}

cpu_temperature 0 {
  format = "T: %degrees °C"
  path = "/sys/class/hwmon/hwmon1/temp1_input"
  max_threshold = 65
  #format_above_threshold = "High CPU Temp : %degrees °C"
}

ethernet eno1 {
  #format_up = "E: %ip (%speed)"
  format_up = "E: up(%speed)"
  format_down = "E: down"
}

wireless wlo1 {
        #format_up = "W: (%quality at %essid, %bitrate) %ip"
        format_up = "W: %essid (%quality) %frequency"
        format_down = "W: down"
}

volume master {
        format = "V: %volume"
        format_muted = "V: muted (%volume)"
        #device = "default"
        #mixer = "Master"
        #mixer_idx = 0
}
