
bind = ALT CTRL, E, submap, eww
submap = eww

bind = , t, exec, eww -c ~/.config/hypr/ewwbar open bar --toggle
bind = , a, exec, eww -c ~/.config/hypr/activate_linux open activate-linux --toggle

bind = , escape, submap, reset
submap = reset
