
bind = ALT CTRL, P, submap, pow
submap = pow

bind = , p, exec, hyprshutdown -t 'Shutting down...' --post-cmd 'shutdown -P 0'
bind = , r, exec, hyprshutdown -t 'Restarting...' --post-cmd 'reboot'
bind = , l, exec, hyprlock -q

bind = , escape, submap, reset
submap = reset

