bind = ALT CTRL, W, submap, wal
submap = wal

bind = , g, exec, ~/.config/hypr/scripts/set_wal.sh ~/.wallpaper/good
bind = , w, exec, ~/.config/hypr/scripts/set_wal.sh ~/.wallpaper/waifu
bind = , v, exec, ~/.config/hypr/scripts/set_wal.sh ~/.wallpaper/vehicle
bind = , l, exec, ~/.config/hypr/scripts/set_wal.sh ~/.wallpaper/landscape
bind = , m, exec, ~/.config/hypr/scripts/set_wal.sh ~/.wallpaper/minimilistic
bind = , s, exec, ~/.config/hypr/scripts/set_wal.sh ~/.wallpaper/scifi

bind = , escape, submap, reset
submap = reset
