unbind C-b
set -g prefix C-f
bind C-f send-prefix

set -g base-index 1
set -g pane-base-index 1

set -g default-terminal "xterm-256color"
set -sg terminal-overrides ",*RGB"

set -g status-style bg=default,fg=white,bright
set -g status-left ""
#set -g status-right "#S"
set -g status-right-length 60
set -g status-right "#{?window_zoomed_flag, |ZOOMED| ,}#S"

set -g window-status-format " #I "
set -g window-status-current-format " #{?window_zoomed_flag, \\/#I/\\ , /#I/}"
set -g renumber-windows on

set -g pane-border-lines simple
set -g mouse
set -g repeat-time 1000
set -s escape-time 0
set -g history-limit 5000

set -g renumber-windows on

# don't do anything when a 'bell' rings
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none

bind r source-file ~/.config/tmux/tmux.conf

unbind '"'
bind | split-window -h
bind z split-window -h -c "#{pane_current_path}"

bind - split-window -v
bind v split-window -v -c "#{pane_current_path}"

bind f resize-pane -Z

bind-key -r k select-pane -U
bind-key -r j select-pane -D
bind-key -r h select-pane -L
bind-key -r l select-pane -R

# Vim-style pane resizing
bind -r H resize-pane -L 1
bind -r J resize-pane -D 1
bind -r K resize-pane -U 1
bind -r L resize-pane -R 1
